version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Onco_data/:/documents/async_api/test_gelios
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=KonstaZ
      - POSTGRES_PASSWORD=gelios
      - POSTGRES_DB=gelios

volumes:
  postgres_data: