# Generated by Django 2.2.16 on 2020-11-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.PositiveIntegerField()),
                ('creator', models.PositiveIntegerField()),
                ('is_free', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=128)),
                ('unit_icon', models.CharField(max_length=512)),
                ('info', models.CharField(max_length=512)),
                ('created_at', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('creator', models.PositiveIntegerField()),
                ('is_admin', models.PositiveSmallIntegerField()),
                ('time_zone', models.PositiveIntegerField()),
                ('cost_mode', models.CharField(max_length=128)),
                ('legal_name', models.CharField(max_length=128)),
                ('lat_lon', models.CharField(max_length=128)),
            ],
        ),
    ]
