# Generated by Django 2.2.16 on 2020-11-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='creator',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='units',
            name='info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='units',
            name='is_free',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='units',
            name='unit_icon',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='creator',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='lat_lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='time_zone',
            field=models.CharField(max_length=64),
        ),
    ]
